# Generated by Django 5.2.3 on 2025-07-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0002_alter_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_avatar',
            field=models.ImageField(blank=True, default='authors/default_avatar.png', upload_to='authors/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(max_length=150),
        ),
    ]
