# Generated by Django 5.2.3 on 2025-08-03 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0003_alter_author_author_avatar_alter_post_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
