# Generated by Django 5.2.3 on 2025-06-19 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0005_alter_blogpost_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={},
        ),
    ]
