# Generated by Django 5.2.3 on 2025-06-19 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0006_alter_blogpost_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at']},
        ),
    ]
