# Generated by Django 5.2.3 on 2025-06-22 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0008_alter_blogpost_options_blogpost_time_since_posted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='time_since_posted',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='HOME.author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='authors/'),
        ),
    ]
